# Site settings
title: Liatris - Determine an object's pose and identity using capacitive touch and RFID technology
email: mwsilliman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Liatris is an open source project that allows an object’s pose and identity to be determined using capacitive touch and RFID technology.
baseurl: "/liatris-org" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  markwsilliman
twitter_username: MWSilliman

# Build settings
markdown: kramdown
permalink: pretty